Terms of use
Organizacao-Docunder/frontend-app pull request #23
Opened 2024-11-13 13:53 UTC by laisrmacedo

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Chore (documentation, packages, or tests updates, nothing that affect the final user directly)
- [ ] Release (new version of the application - only for production)

## Description

- A checkbox has been created to confirm agreement with the terms of use. 
- The button to continue is available if the checkbox is selected. Tests should verify this new functionality.
- llustrative style for the button to indicate that the user can only proceed with account creation if they agree to the terms. Must be reviewed by UX/UI.
- Text of the platform's "Terms and Conditions of Use" and "Privacy Policies" updated.

## Screenshots

Screenshot if needed.

## Tasks

- #TASK-ID - Task Name

## Dependencies

This pull request has a dependency on the following others:

- link-to-depency PR or N/A

2024-11-13 20:40 UTC, junioralvesbr approved these changes

2024-11-19 04:59 UTC, rodrigomolter requested changes

2024-11-19 04:59 UTC, rodrigomolter commented on nextjs-app/src/app/signup/components/ModalTerms.tsx
> +            5.1 Implementamos medidas de segurança para proteger suas informações pessoais contra acesso não autorizado, alteração, divulgação ou destruição. Realizamos uma atualização obrigatória de
This `(Novo Requisito SCRUM 50)` is not necessary in the Terms of Use.

2024-11-19 04:59 UTC, rodrigomolter commented on nextjs-app/src/app/signup/components/ModalTerms.tsx
> +            2.1. Este website possui  o seu código fonte disponível no <a className="text-primary-1" href="https://github.com/Organizacao-Docunder/App">GitHub</a> sob a licença de uso de Código Abert
It would be cool if this link **Github** opened in a new tab (`target="_blank"`)

2024-11-19 04:59 UTC, rodrigomolter commented on nextjs-app/src/app/signup/components/ModalTerms.tsx
> +            2.2. Para saber mais, acesse o link: <a className="text-primary-1" href="https://github.com/Organizacao-Docunder/App/blob/main/LICENSE">https://github.com/Organizacao-Docunder/App/blob/ma
It would be cool if this link opened in a new tab (`target="_blank"`)

2024-11-19 13:29 UTC, laisrmacedo commented on nextjs-app/src/app/signup/components/ModalTerms.tsx
> +            5.1 Implementamos medidas de segurança para proteger suas informações pessoais contra acesso não autorizado, alteração, divulgação ou destruição. Realizamos uma atualização obrigatória de
So this "Security" topic should be deleted?

2024-11-19 20:45 UTC, rodrigomolter approved these changes

2024-11-19 20:48 UTC, merged